import type { Config } from "tailwindcss";
import { heroui } from "@heroui/theme";

const config: Config = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: ["class", '[data-theme="dark"]'],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-sans)"],
        display: ["var(--font-display)"],
        mono: ["var(--font-mono)"],
      },
      fontSize: {
        "step--2": "0.6875rem",
        "step--1": "0.8125rem",
        "step-0": "1rem",
        "step-1": "clamp(1.125rem, 1.08rem + 0.22vw, 1.2rem)",
        "step-2": "clamp(1.3125rem, 1.22rem + 0.46vw, 1.44rem)",
        "step-3": "clamp(1.5rem, 1.34rem + 0.8vw, 1.728rem)",
        "step-4": "clamp(1.75rem, 1.47rem + 1.38vw, 2.0736rem)",
        "step-5": "clamp(2rem, 1.56rem + 2.2vw, 2.4883rem)",
        "step-6": "clamp(2.375rem, 1.72rem + 3.28vw, 2.986rem)",
        "display-xl": "clamp(3rem, 1.1rem + 8.2vw, 6.25rem)",
        "ui-md": "0.9375rem",
        "ui-sm": "0.875rem",
        "ui-xs": "0.8125rem",
        data: "0.8125rem",
        "data-sm": "0.6875rem",
      },
      maxWidth: {
        container: "1440px",
        shop: "1440px",
        narrow: "1100px",
        wide: "1600px",
        read: "640px",
      },
      spacing: {
        gutter: "var(--gutter)",
      },
      colors: {
        surface: {
          DEFAULT: "var(--color-bg)",
          1: "var(--color-bg-secondary)",
          2: "var(--color-bg-tertiary)",
          warm: "var(--color-bg-warm)",
        },
        mount: "var(--color-mount)",
        raised: "var(--color-raised)",
        fascia: "var(--color-fascia)",
        skirting: "var(--color-skirting)",
        ink: {
          DEFAULT: "var(--color-text)",
          muted: "var(--color-text-secondary)",
          faint: "var(--color-text-tertiary)",
          subtle: "var(--color-text-tertiary)",
        },
        brand: {
          DEFAULT: "var(--color-accent)",
          hover: "var(--color-accent-hover)",
          wash: "var(--color-accent-light)",
          soft: "var(--color-accent-light)",
        },
        "on-brand": "var(--color-on-accent)",
        "accent-ink": "var(--color-accent-ink)",
        sale: "var(--color-accent-3)",
        rule: "var(--color-rule)",
        rail: "var(--color-rail)",
        wire: "var(--color-wire)",
        line: {
          DEFAULT: "var(--color-border)",
          hover: "var(--color-border-hover)",
        },
        control: "var(--color-border-control)",
        focus: "var(--color-focus)",
        scrim: "var(--color-scrim)",
        rarity: {
          DEFAULT: "var(--rarity)",
          consumer: "var(--rarity-consumer)",
          industrial: "var(--rarity-industrial)",
          milspec: "var(--rarity-milspec)",
          restricted: "var(--rarity-restricted)",
          classified: "var(--rarity-classified)",
          covert: "var(--rarity-covert)",
          gold: "var(--rarity-gold)",
        },
        success: { DEFAULT: "var(--color-success)", wash: "var(--color-success-wash)" },
        warning: { DEFAULT: "var(--color-warning)", wash: "var(--color-warning-wash)" },
        danger: { DEFAULT: "var(--color-danger)", wash: "var(--color-danger-wash)" },
        info: { DEFAULT: "var(--color-info)", wash: "var(--color-info-wash)" },
        "on-danger": "var(--color-on-danger)",
      },
      boxShadow: {
        card: "var(--shadow-card)",
        "card-hover": "var(--shadow-card-hover)",
        accent: "var(--shadow-accent)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        panel: "var(--shadow-panel)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        pill: "var(--radius-pill)",
        control: "var(--radius-control)",
      },
      transitionTimingFunction: {
        hang: "var(--ease-hang)",
        settle: "var(--ease-settle)",
        std: "cubic-bezier(0.4, 0, 0.2, 1)",
        "in-out-strong": "cubic-bezier(0.65, 0, 0.35, 1)",
      },
      transitionDuration: {
        micro: "120ms",
        ui: "220ms",
        panel: "300ms",
        reveal: "760ms",
      },
      zIndex: {
        lot: "1",
        sticky: "40",
        dropdown: "50",
        drawer: "60",
        modal: "70",
        toast: "80",
        cookie: "90",
      },
      backgroundImage: {
        "spot-rake": "var(--spot-rake)",
      },
    },
  },
  plugins: [
    heroui({
      layout: { radius: { small: "0px", medium: "0px", large: "0px" } },
      themes: {
        light: { colors: { background: "#F8F5EF", foreground: "#221E1A", primary: { DEFAULT: "#86203A", foreground: "#FBF6F0" } } },
        dark: { colors: { background: "#231E1A", foreground: "#EFE8DD", primary: { DEFAULT: "#A82B3B", foreground: "#FFF4EF" } } },
      },
    }),
  ],
};

export default config;
